#!/bin/sh

until mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -D $MYSQL_DATABASE --silent -e "show databases;"
do
  echo "Waiting for database connection..."
  sleep 5
done

diesel migration run
cargo watch --exec run
